CREATE TABLE venues (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    venue_name TEXT NOT NULL,
    zipcode TEXT,
    website TEXT,
    date_published TIMESTAMP DEFAULT now() NOT NULL
);